# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Kami.Repo.insert!(%Kami.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

{_, admin} = Kami.Accounts.create_admin(%{name: "admin", password: "password"})
{_, alice} = Kami.Accounts.create_user(%{name: "alice", password: "password", last_location_id: 1})
{_, bob} = Kami.Accounts.create_user(%{name: "bob", password: "password", last_location_id: 2})

{_, arisu} = Kami.Accounts.create_character(alice, %{
  name: "Arisu",
  clan: "Crane",
  family: "Doji",
  school: "Diplomat",
  school_rank: 1,
  air: 3,
  water: 2,
  earth: 1,
  fire: 2,
  void: 2,
  void_points: 1,
  void_points_max: 2,
  honor: 30,
  glory: 30,
  status: 30,
  public_description: "Blah blah blah",
  ninjo: "a ninjo goes here",
  giri: "a giri goes here",
  weapons: "some weapons go here",
  armor: "some armor goes here",
  anxieties: "life is tough",
  outburst: "aw fuuuuck",
  passions: "tea sure is great",
  distinctions: "im real awesome",
  adversities: "allergic to katanas",
  titles: "idk samurai i guess",
  questions: "boy howdy a whole shitload of text will go here",
  techniques: "talk real good",
  images: ["image01.jpg", "image02.jpg"],
  xp: 0,
  bxp: 0,
  bxp_this_week: 0,
  total_xp: 0,
  total_spent_xp: 0,
  approved: true,
  skill_aesthetics: 1,
  skill_composition: 1,
  skill_design: 1,
  skill_smithing: 1,
  skill_fitness: 1,
  skill_melee: 1,
  skill_ranged: 1,
  skill_unarmed: 1,
  skill_iaijutsu: 1,
  skill_meditation: 1,
  skill_tactics: 1,
  skill_command: 1,
  skill_courtesy: 1,
  skill_games: 1,
  skill_performance: 1,
  skill_culture: 1,
  skill_government: 1,
  skill_sentiment: 1,
  skill_theology: 1,
  skill_medicine: 1,
  skill_commerce: 1,
  skill_labor: 1,
  skill_seafaring: 1,
  skill_skullduggery: 1,
  skill_survival: 1,
  strife: 0,
  })
{_, hiroto} = Kami.Accounts.create_character(bob, %{
  name: "Hiroto",
  clan: "Lion",
  family: "Akodo",
  school: "Beefslab",
  school_rank: 1,
  air: 3,
  water: 2,
  earth: 1,
  fire: 2,
  void: 2,
  void_points: 1,
  void_points_max: 2,
  honor: 30,
  glory: 30,
  status: 30,
  public_description: "Bloo bloo bloo",
  ninjo: "a ninjo goes here",
  giri: "a giri goes here",
  weapons: "some weapons go here",
  armor: "some armor goes here",
  anxieties: "life is tough",
  outburst: "aw fuuuuck",
  passions: "tea sure is great",
  distinctions: "im real awesome",
  adversities: "allergic to katanas",
  titles: "idk samurai i guess",
  questions: "boy howdy a whole shitload of text will go here",
  techniques: "talk real good",
  images: ["image01.jpg", "image02.jpg"],
  xp: 0,
  bxp: 0,
  bxp_this_week: 0,
  total_xp: 0,
  total_spent_xp: 0,
  approved: true,
  skill_aesthetics: 1,
  skill_composition: 1,
  skill_design: 1,
  skill_smithing: 1,
  skill_fitness: 1,
  skill_melee: 1,
  skill_ranged: 1,
  skill_unarmed: 1,
  skill_iaijutsu: 1,
  skill_meditation: 1,
  skill_tactics: 1,
  skill_command: 1,
  skill_courtesy: 1,
  skill_games: 1,
  skill_performance: 1,
  skill_culture: 1,
  skill_government: 1,
  skill_sentiment: 1,
  skill_theology: 1,
  skill_medicine: 1,
  skill_commerce: 1,
  skill_labor: 1,
  skill_seafaring: 1,
  skill_skullduggery: 1,
  skill_survival: 1,
  strife: 0,  
  })
{_, npc1} = Kami.Accounts.create_character(admin, %{
  name: "NPC1",
  clan: "Scorpion",
  family: "Bayushi",
  school: "Untrustworthy",
  school_rank: 1,
  air: 3,
  water: 2,
  earth: 1,
  fire: 2,
  void: 2,
  void_points: 1,
  void_points_max: 2,
  honor: 30,
  glory: 30,
  status: 30,
  public_description: "Bloo bloo bloo",
  ninjo: "a ninjo goes here",
  giri: "a giri goes here",
  weapons: "some weapons go here",
  armor: "some armor goes here",
  anxieties: "life is tough",
  outburst: "aw fuuuuck",
  passions: "tea sure is great",
  distinctions: "im real awesome",
  adversities: "allergic to katanas",
  titles: "idk samurai i guess",
  questions: "boy howdy a whole shitload of text will go here",
  techniques: "talk real good",
  images: ["image01.jpg", "image02.jpg"],
  xp: 0,
  bxp: 0,
  bxp_this_week: 0,
  total_xp: 0,
  total_spent_xp: 0,
  approved: true,
  skill_aesthetics: 1,
  skill_composition: 1,
  skill_design: 1,
  skill_smithing: 1,
  skill_fitness: 1,
  skill_melee: 1,
  skill_ranged: 1,
  skill_unarmed: 1,
  skill_iaijutsu: 1,
  skill_meditation: 1,
  skill_tactics: 1,
  skill_command: 1,
  skill_courtesy: 1,
  skill_games: 1,
  skill_performance: 1,
  skill_culture: 1,
  skill_government: 1,
  skill_sentiment: 1,
  skill_theology: 1,
  skill_medicine: 1,
  skill_commerce: 1,
  skill_labor: 1,
  skill_seafaring: 1,
  skill_skullduggery: 1,
  skill_survival: 1,
  strife: 0,  
  })
{_, npc2} = Kami.Accounts.create_character(admin, %{
  name: "NPC2",
  clan: "Scorpion",
  family: "Bayushi",
  school: "Untrustworthy",
  school_rank: 1,
  air: 3,
  water: 2,
  earth: 1,
  fire: 2,
  void: 2,
  void_points: 1,
  void_points_max: 2,
  honor: 30,
  glory: 30,
  status: 30,
  public_description: "Bloo bloo bloo",
  ninjo: "a ninjo goes here",
  giri: "a giri goes here",
  weapons: "some weapons go here",
  armor: "some armor goes here",
  anxieties: "life is tough",
  outburst: "aw fuuuuck",
  passions: "tea sure is great",
  distinctions: "im real awesome",
  adversities: "allergic to katanas",
  titles: "idk samurai i guess",
  questions: "boy howdy a whole shitload of text will go here",
  techniques: "talk real good",
  images: ["image01.jpg", "image02.jpg"],
  xp: 0,
  bxp: 0,
  bxp_this_week: 0,
  total_xp: 0,
  total_spent_xp: 0,
  approved: true,
  skill_aesthetics: 1,
  skill_composition: 1,
  skill_design: 1,
  skill_smithing: 1,
  skill_fitness: 1,
  skill_melee: 1,
  skill_ranged: 1,
  skill_unarmed: 1,
  skill_iaijutsu: 1,
  skill_meditation: 1,
  skill_tactics: 1,
  skill_command: 1,
  skill_courtesy: 1,
  skill_games: 1,
  skill_performance: 1,
  skill_culture: 1,
  skill_government: 1,
  skill_sentiment: 1,
  skill_theology: 1,
  skill_medicine: 1,
  skill_commerce: 1,
  skill_labor: 1,
  skill_seafaring: 1,
  skill_skullduggery: 1,
  skill_survival: 1,
  strife: 0,  
  })    
{_, npc3} = Kami.Accounts.create_character(admin, %{
  name: "NPC3",
  clan: "Scorpion",
  family: "Bayushi",
  school: "Untrustworthy",
  school_rank: 1,
  air: 3,
  water: 2,
  earth: 1,
  fire: 2,
  void: 2,
  void_points: 1,
  void_points_max: 2,
  honor: 30,
  glory: 30,
  status: 30,
  public_description: "Bloo bloo bloo",
  ninjo: "a ninjo goes here",
  giri: "a giri goes here",
  weapons: "some weapons go here",
  armor: "some armor goes here",
  anxieties: "life is tough",
  outburst: "aw fuuuuck",
  passions: "tea sure is great",
  distinctions: "im real awesome",
  adversities: "allergic to katanas",
  titles: "idk samurai i guess",
  questions: "boy howdy a whole shitload of text will go here",
  techniques: "talk real good",
  images: ["image01.jpg", "image02.jpg"],
  xp: 0,
  bxp: 0,
  bxp_this_week: 0,
  total_xp: 0,
  total_spent_xp: 0,
  approved: true,
  skill_aesthetics: 1,
  skill_composition: 1,
  skill_design: 1,
  skill_smithing: 1,
  skill_fitness: 1,
  skill_melee: 1,
  skill_ranged: 1,
  skill_unarmed: 1,
  skill_iaijutsu: 1,
  skill_meditation: 1,
  skill_tactics: 1,
  skill_command: 1,
  skill_courtesy: 1,
  skill_games: 1,
  skill_performance: 1,
  skill_culture: 1,
  skill_government: 1,
  skill_sentiment: 1,
  skill_theology: 1,
  skill_medicine: 1,
  skill_commerce: 1,
  skill_labor: 1,
  skill_seafaring: 1,
  skill_skullduggery: 1,
  skill_survival: 1,
  strife: 0,  
  })
  
{_, meido} = Kami.World.create_location(%{name: "Meido", description: "OOC shit happens here", locked: false, ooc: true})
{_, ic1} = Kami.World.create_location(meido, %{name: "IC Location 1", description: "Some IC shit happens here", locked: false, ooc: false})
{_, ic2} = Kami.World.create_location(meido, %{name: "IC Location 2", description: "Some IC shit happens here", locked: false, ooc: false})
{_, ic3} = Kami.World.create_location(meido, %{name: "IC Location 3", description: "Some IC shit happens here", locked: false, ooc: false})
{_, ic4} = Kami.World.create_location(ic3, %{name: "IC Location 4", description: "Some IC shit happens here", locked: false, ooc: false})
{_, ic5} = Kami.World.create_location(ic4, %{name: "IC Location 5", description: "Some IC shit happens here", locked: false, ooc: false})
{_, ic6} = Kami.World.create_location(ic4, %{name: "IC Location 6", description: "Some IC shit happens here", locked: false, ooc: false})


Kami.World.create_post(meido, %{ooc: true, narrative: true, text: "This! This is a narrative text post. It's very exciting, isn't it?"})
Kami.World.create_post(meido, %{ooc: true, narrative: false, text: "This, by contrast, is a character text post.", glory: 20, honor: 20, status: 20, name: "Hiroto", image: "image01.png"})
Kami.World.create_post(meido, %{ooc: true, narrative: false, text: "And this is a character text post with a dice roll result.", glory: 30, honor: 30, status: 30, name: "Arisu", image: "image02.png", diceroll: true, skillroll: true, ring_name: "Air", ring_value: 3, skill_name: "Courtesy", results: [0, 3, 4, 10, 16, 8]})
Kami.World.create_post(meido, %{ooc: true, narrative: true, text: "And now we have a narrative rolling a d100 for no reason.", diceroll: true, die_size: 100, results: [100]})
